# Generated by Django 4.2 on 2023-06-15 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('titorovka', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductionOutput1',
            new_name='ProductionOutput31',
        ),
        migrations.RenameModel(
            old_name='ProductionOutput3',
            new_name='ProductionOutput33',
        ),
        migrations.RenameModel(
            old_name='Table3',
            new_name='Table31',
        ),
        migrations.DeleteModel(
            name='Table1',
        ),
    ]
