# Generated by Django 4.2 on 2023-06-05 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titorovka', '0002_tabletest'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionOutput31',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Дата')),
                ('time', models.TimeField(verbose_name='Время')),
                ('production', models.IntegerField(verbose_name='Продукция линии')),
            ],
            options={
                'verbose_name_plural': 'Выпуск продукции линии 31',
            },
        ),
        migrations.CreateModel(
            name='Speed31',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Дата')),
                ('time', models.TimeField(verbose_name='Время')),
                ('depal', models.IntegerField(blank=True, default=0.0, null=True, verbose_name='Скорость депалитизатор')),
                ('triblok', models.IntegerField(blank=True, default=0.0, null=True, verbose_name='Скорость триблок')),
                ('kapsula', models.IntegerField(blank=True, default=0.0, null=True, verbose_name='Скорость капсулятора')),
                ('eticetka', models.IntegerField(blank=True, default=0.0, null=True, verbose_name='Скорость этикетки')),
                ('ukladchik', models.IntegerField(blank=True, default=0.0, null=True, verbose_name='Скорость укладчика')),
                ('zakleichik', models.IntegerField(blank=True, default=0.0, null=True, verbose_name='Скорость заклейщика')),
            ],
            options={
                'verbose_name_plural': 'Производительность линии 31',
            },
        ),
        migrations.RenameModel(
            old_name='TableTest',
            new_name='Table31',
        ),
        migrations.AlterModelOptions(
            name='table31',
            options={'verbose_name_plural': 'Простои 31 линии'},
        ),
    ]
