# Generated by Django 4.2 on 2023-06-26 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('titorovka', '0003_speed31_speed33'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productionoutput33',
            options={'verbose_name_plural': 'Выпуск продукции линии 33'},
        ),
        migrations.AlterModelOptions(
            name='speed31',
            options={'verbose_name_plural': 'Производительность линии 31'},
        ),
        migrations.AlterModelOptions(
            name='speed33',
            options={'verbose_name_plural': 'Производительность линии 33'},
        ),
    ]
