# Generated by Django 4.2 on 2023-06-06 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('titorovka', '0003_productionoutput31_speed31_rename_tabletest_table31_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Speed31',
        ),
    ]
