# Generated by Django 4.2 on 2023-06-06 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titorovka', '0004_delete_speed31'),
    ]

    operations = [
        migrations.CreateModel(
            name='Speed31',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Дата')),
                ('time', models.TimeField(verbose_name='Время')),
                ('depal', models.IntegerField(blank=True, default=0.0, null=True, verbose_name='Скорость депалитизатор')),
                ('triblok', models.IntegerField(blank=True, default=0.0, null=True, verbose_name='Скорость триблок')),
                ('kapsula', models.IntegerField(blank=True, default=0.0, null=True, verbose_name='Скорость капсулятора')),
                ('eticetka', models.IntegerField(blank=True, default=0.0, null=True, verbose_name='Скорость этикетки')),
                ('ukladchik', models.IntegerField(blank=True, default=0.0, null=True, verbose_name='Скорость укладчика')),
                ('zakleichik', models.IntegerField(blank=True, default=0.0, null=True, verbose_name='Скорость заклейщика')),
            ],
            options={
                'verbose_name_plural': 'Производительность линии 4',
            },
        ),
    ]
