# Generated by Django 4.2 on 2023-07-10 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titorovka', '0005_productionoutput24_speed24_speed26_table24_table26'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionOutput26',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Дата')),
                ('time', models.TimeField(verbose_name='Время')),
                ('production', models.IntegerField(verbose_name='Продукция линии')),
            ],
            options={
                'verbose_name_plural': 'Выпуск продукции линии 33',
            },
        ),
    ]
