# Generated by Django 4.2 on 2023-06-06 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('titorovka', '0006_speed33_delete_titorovka_alter_speed31_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Speed33',
            new_name='Speed4',
        ),
    ]
