# Generated by Django 4.2 on 2023-07-10 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titorovka', '0006_productionoutput26'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionOutput25',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Дата')),
                ('time', models.TimeField(verbose_name='Время')),
                ('production', models.IntegerField(verbose_name='Продукция линии')),
            ],
            options={
                'verbose_name_plural': 'Выпуск продукции линии 24',
            },
        ),
        migrations.CreateModel(
            name='Speed25',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Дата')),
                ('time', models.TimeField(verbose_name='Время')),
                ('depal', models.IntegerField(blank=True, default=0.0, null=True, verbose_name='Скорость депалитизатор')),
                ('triblok', models.IntegerField(blank=True, default=0.0, null=True, verbose_name='Скорость триблок')),
                ('kapsula', models.IntegerField(blank=True, default=0.0, null=True, verbose_name='Скорость капсулятора')),
                ('eticetka', models.IntegerField(blank=True, default=0.0, null=True, verbose_name='Скорость этикетки')),
                ('ukladchik', models.IntegerField(blank=True, default=0.0, null=True, verbose_name='Скорость укладчика')),
                ('zakleichik', models.IntegerField(blank=True, default=0.0, null=True, verbose_name='Скорость заклейщика')),
            ],
            options={
                'verbose_name_plural': 'Производительность линии 25',
            },
        ),
        migrations.CreateModel(
            name='Table25',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startdata', models.DateField(verbose_name='Дата начала простоя')),
                ('starttime', models.TimeField(verbose_name='Время начала простоя')),
                ('prostoy', models.TimeField(blank=True, null=True, verbose_name='Время простоя')),
                ('uchastok', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Где произошол простой')),
                ('prichina', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Причина')),
                ('otv_pod', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Ответственное подразделение')),
                ('comment', models.CharField(blank=True, default=' ', max_length=250, null=True, verbose_name='Комментарий')),
            ],
            options={
                'verbose_name_plural': 'Простои 25 линии',
            },
        ),
        migrations.AlterModelOptions(
            name='productionoutput24',
            options={'verbose_name_plural': 'Выпуск продукции линии 24'},
        ),
        migrations.AlterModelOptions(
            name='productionoutput26',
            options={'verbose_name_plural': 'Выпуск продукции линии 26'},
        ),
        migrations.AlterModelOptions(
            name='speed24',
            options={'verbose_name_plural': 'Производительность линии 24'},
        ),
        migrations.AlterModelOptions(
            name='speed26',
            options={'verbose_name_plural': 'Производительность линии 26'},
        ),
        migrations.AlterModelOptions(
            name='table24',
            options={'verbose_name_plural': 'Простои 24 линии'},
        ),
        migrations.AlterModelOptions(
            name='table26',
            options={'verbose_name_plural': 'Простои 26 линии'},
        ),
    ]
