# Generated by Django 4.2 on 2023-06-06 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('titorovka', '0007_rename_speed33_speed4'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductionOutput31',
            new_name='ProductionOutput1',
        ),
        migrations.RenameModel(
            old_name='Speed31',
            new_name='Speed1',
        ),
        migrations.RenameModel(
            old_name='Table31',
            new_name='Table1',
        ),
        migrations.DeleteModel(
            name='Speed4',
        ),
        migrations.AlterModelOptions(
            name='speed1',
            options={'verbose_name_plural': 'Производительность линии 33'},
        ),
    ]
