# Generated by Django 4.2 on 2023-09-05 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('titorovka', '0007_productionoutput25_speed25_table25_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productionoutput25',
            options={'verbose_name_plural': 'Выпуск продукции линии 25'},
        ),
    ]
