# Generated by Django 4.2 on 2023-11-28 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titorovka', '0008_alter_productionoutput25_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='SetProductionSpeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameProduct', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Наименование продукта')),
                ('speed', models.IntegerField(verbose_name='Скорость')),
            ],
            options={
                'verbose_name_plural': 'Установленная скорость по продукту',
            },
        ),
    ]
