# Generated by Django 4.2 on 2023-11-28 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titorovka', '0009_setproductionspeed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setproductionspeed',
            name='nameProduct',
            field=models.CharField(blank=True, default='', max_length=150, null=True, verbose_name='Наименование продукта'),
        ),
    ]
