# Generated by Django 4.2 on 2023-11-28 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titorovka', '0011_alter_setproductionspeed_speed'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionTime31',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Дата')),
                ('time', models.TimeField(verbose_name='Время')),
                ('nameProduct', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Наименование продукта')),
            ],
            options={
                'verbose_name_plural': 'Время работы на продукте',
            },
        ),
        migrations.RenameModel(
            old_name='SetProductionSpeed',
            new_name='SetProductionSpeed31',
        ),
    ]
