# Generated by Django 4.2 on 2023-11-28 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titorovka', '0012_productiontime31_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productiontime31',
            name='nameProduct',
            field=models.CharField(blank=True, default='', max_length=150, null=True, verbose_name='Наименование продукта'),
        ),
    ]
