# Generated by Django 4.2 on 2024-02-06 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titorovka', '0013_alter_productiontime31_nameproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='speed24',
            name='Guid_Prichina',
            field=models.CharField(blank=True, default='Не определено', max_length=36, null=True, verbose_name='Guid причины'),
        ),
        migrations.AddField(
            model_name='speed24',
            name='Guid_Uchastok',
            field=models.CharField(blank=True, default='Не определено', max_length=36, null=True, verbose_name='Guid участок'),
        ),
        migrations.AddField(
            model_name='speed25',
            name='Guid_Prichina',
            field=models.CharField(blank=True, default='Не определено', max_length=36, null=True, verbose_name='Guid причины'),
        ),
        migrations.AddField(
            model_name='speed25',
            name='Guid_Uchastok',
            field=models.CharField(blank=True, default='Не определено', max_length=36, null=True, verbose_name='Guid участок'),
        ),
        migrations.AddField(
            model_name='speed26',
            name='Guid_Prichina',
            field=models.CharField(blank=True, default='Не определено', max_length=36, null=True, verbose_name='Guid причины'),
        ),
        migrations.AddField(
            model_name='speed26',
            name='Guid_Uchastok',
            field=models.CharField(blank=True, default='Не определено', max_length=36, null=True, verbose_name='Guid участок'),
        ),
        migrations.AddField(
            model_name='speed31',
            name='Guid_Prichina',
            field=models.CharField(blank=True, default='Не определено', max_length=36, null=True, verbose_name='Guid причины'),
        ),
        migrations.AddField(
            model_name='speed31',
            name='Guid_Uchastok',
            field=models.CharField(blank=True, default='Не определено', max_length=36, null=True, verbose_name='Guid участок'),
        ),
        migrations.AddField(
            model_name='speed33',
            name='Guid_Prichina',
            field=models.CharField(blank=True, default='Не определено', max_length=36, null=True, verbose_name='Guid причины'),
        ),
        migrations.AddField(
            model_name='speed33',
            name='Guid_Uchastok',
            field=models.CharField(blank=True, default='Не определено', max_length=36, null=True, verbose_name='Guid участок'),
        ),
    ]
