# Generated by Django 4.2 on 2024-02-06 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titorovka', '0014_speed24_guid_prichina_speed24_guid_uchastok_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='speed24',
            name='Guid_Prichina',
        ),
        migrations.RemoveField(
            model_name='speed24',
            name='Guid_Uchastok',
        ),
        migrations.RemoveField(
            model_name='speed25',
            name='Guid_Prichina',
        ),
        migrations.RemoveField(
            model_name='speed25',
            name='Guid_Uchastok',
        ),
        migrations.RemoveField(
            model_name='speed26',
            name='Guid_Prichina',
        ),
        migrations.RemoveField(
            model_name='speed26',
            name='Guid_Uchastok',
        ),
        migrations.RemoveField(
            model_name='speed31',
            name='Guid_Prichina',
        ),
        migrations.RemoveField(
            model_name='speed31',
            name='Guid_Uchastok',
        ),
        migrations.RemoveField(
            model_name='speed33',
            name='Guid_Prichina',
        ),
        migrations.RemoveField(
            model_name='speed33',
            name='Guid_Uchastok',
        ),
        migrations.AddField(
            model_name='table24',
            name='Guid_Prichina',
            field=models.CharField(blank=True, default='Не определено', max_length=36, null=True, verbose_name='Guid причины'),
        ),
        migrations.AddField(
            model_name='table24',
            name='Guid_Uchastok',
            field=models.CharField(blank=True, default='Не определено', max_length=36, null=True, verbose_name='Guid участок'),
        ),
        migrations.AddField(
            model_name='table25',
            name='Guid_Prichina',
            field=models.CharField(blank=True, default='Не определено', max_length=36, null=True, verbose_name='Guid причины'),
        ),
        migrations.AddField(
            model_name='table25',
            name='Guid_Uchastok',
            field=models.CharField(blank=True, default='Не определено', max_length=36, null=True, verbose_name='Guid участок'),
        ),
        migrations.AddField(
            model_name='table26',
            name='Guid_Prichina',
            field=models.CharField(blank=True, default='Не определено', max_length=36, null=True, verbose_name='Guid причины'),
        ),
        migrations.AddField(
            model_name='table26',
            name='Guid_Uchastok',
            field=models.CharField(blank=True, default='Не определено', max_length=36, null=True, verbose_name='Guid участок'),
        ),
        migrations.AddField(
            model_name='table31',
            name='Guid_Prichina',
            field=models.CharField(blank=True, default='Не определено', max_length=36, null=True, verbose_name='Guid причины'),
        ),
        migrations.AddField(
            model_name='table31',
            name='Guid_Uchastok',
            field=models.CharField(blank=True, default='Не определено', max_length=36, null=True, verbose_name='Guid участок'),
        ),
        migrations.AddField(
            model_name='table33',
            name='Guid_Prichina',
            field=models.CharField(blank=True, default='Не определено', max_length=36, null=True, verbose_name='Guid причины'),
        ),
        migrations.AddField(
            model_name='table33',
            name='Guid_Uchastok',
            field=models.CharField(blank=True, default='Не определено', max_length=36, null=True, verbose_name='Guid участок'),
        ),
    ]
