# Generated by Django 4.2 on 2024-02-07 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titorovka', '0015_remove_speed24_guid_prichina_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table31',
            name='uchastok',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Где произошол простой'),
        ),
        migrations.AlterField(
            model_name='table33',
            name='uchastok',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Где произошол простой'),
        ),
    ]
