# Generated by Django 4.2 on 2024-03-18 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titorovka', '0017_alter_table31_prichina'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionTime33',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Дата')),
                ('time', models.TimeField(verbose_name='Время')),
                ('type_bottle', models.CharField(blank=True, default='', max_length=150, null=True, verbose_name='Тип бутылки')),
            ],
            options={
                'verbose_name_plural': 'Время работы на бутылке 33',
            },
        ),
    ]
