# Generated by Django 4.2 on 2024-03-18 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titorovka', '0018_productiontime33'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SetProductionSpeed31',
        ),
        migrations.AlterModelOptions(
            name='productiontime31',
            options={'verbose_name_plural': 'Время работы на бутылке 31'},
        ),
        migrations.RemoveField(
            model_name='productiontime31',
            name='nameProduct',
        ),
        migrations.AddField(
            model_name='productiontime31',
            name='type_bottle',
            field=models.CharField(blank=True, default='', max_length=150, null=True, verbose_name='Тип бутылки'),
        ),
    ]
