# Generated by Django 4.2 on 2024-03-20 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titorovka', '0019_delete_setproductionspeed31_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionTime24',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Дата')),
                ('time', models.TimeField(verbose_name='Время')),
                ('type_bottle', models.CharField(blank=True, default='', max_length=150, null=True, verbose_name='Тип бутылки')),
            ],
            options={
                'verbose_name_plural': 'Время работы на бутылке 24',
            },
        ),
        migrations.CreateModel(
            name='ProductionTime25',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Дата')),
                ('time', models.TimeField(verbose_name='Время')),
                ('type_bottle', models.CharField(blank=True, default='', max_length=150, null=True, verbose_name='Тип бутылки')),
            ],
            options={
                'verbose_name_plural': 'Время работы на бутылке 25',
            },
        ),
        migrations.CreateModel(
            name='ProductionTime26',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Дата')),
                ('time', models.TimeField(verbose_name='Время')),
                ('type_bottle', models.CharField(blank=True, default='', max_length=150, null=True, verbose_name='Тип бутылки')),
            ],
            options={
                'verbose_name_plural': 'Время работы на бутылке 26',
            },
        ),
    ]
