# Generated by Django 4.2 on 2023-04-28 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bottleExplosion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Дата')),
                ('time', models.TimeField(verbose_name='Время')),
                ('bottle', models.IntegerField(verbose_name='Взрыв')),
            ],
            options={
                'verbose_name_plural': 'Взрывы бутылок',
            },
        ),
        migrations.CreateModel(
            name='bottling_plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Registrar', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Регистратор')),
                ('GUIDDocument', models.CharField(blank=True, default='', max_length=36, null=True, verbose_name='GUIDDocument')),
                ('Data', models.DateField(verbose_name='Дата')),
                ('GIUDLine', models.CharField(blank=True, default='', max_length=36, null=True, verbose_name='GIUDLine')),
                ('ShiftNumber', models.IntegerField(verbose_name='Номер смены')),
                ('GUIDNomenсlature', models.CharField(blank=True, default=' ', max_length=36, null=True, verbose_name='GUIDNomenсlature')),
                ('Quantity', models.IntegerField(verbose_name='Количество')),
            ],
            options={
                'verbose_name_plural': 'План розлива',
            },
        ),
        migrations.CreateModel(
            name='Line',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GUID', models.CharField(max_length=36, verbose_name='GUID')),
                ('Line', models.CharField(max_length=50, verbose_name='Название линии')),
                ('Podrazdelenie', models.CharField(max_length=150, verbose_name='Подразделение')),
                ('PodrazdeleniePloshadka', models.CharField(max_length=150, verbose_name='ПодразделениеПлощадка')),
                ('NomerLine', models.IntegerField(verbose_name='Номер линии')),
            ],
            options={
                'verbose_name_plural': 'Линии',
            },
        ),
        migrations.CreateModel(
            name='NapAcratofori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Дата')),
                ('time', models.TimeField(verbose_name='Время')),
                ('acr62_temp', models.FloatField(blank=True, default=0.0, null=True, verbose_name='Температура 62')),
                ('acr62_press', models.FloatField(blank=True, default=0.0, null=True, verbose_name='Давление 62')),
                ('acr62_volume', models.FloatField(blank=True, default=0.0, null=True, verbose_name='Обьем 62')),
                ('acr63_temp', models.FloatField(blank=True, default=0.0, null=True, verbose_name='Температура 63')),
                ('acr63_press', models.FloatField(blank=True, default=0.0, null=True, verbose_name='Давление 63')),
                ('acr63_volume', models.FloatField(blank=True, default=0.0, null=True, verbose_name='Обьем 63')),
                ('acr64_temp', models.FloatField(blank=True, default=0.0, null=True, verbose_name='Температура 64')),
                ('acr64_press', models.FloatField(blank=True, default=0.0, null=True, verbose_name='Давление 64')),
                ('acr64_volume', models.FloatField(blank=True, default=0.0, null=True, verbose_name='Обьем 64')),
                ('acr65_temp', models.FloatField(blank=True, default=0.0, null=True, verbose_name='Температура 65')),
                ('acr65_press', models.FloatField(blank=True, default=0.0, null=True, verbose_name='Давление 65')),
                ('acr65_volume', models.FloatField(blank=True, default=0.0, null=True, verbose_name='Обьем 65')),
                ('acr66_temp', models.FloatField(blank=True, default=0.0, null=True, verbose_name='Температура 66')),
                ('acr66_press', models.FloatField(blank=True, default=0.0, null=True, verbose_name='Давление 66')),
                ('acr66_volume', models.FloatField(blank=True, default=0.0, null=True, verbose_name='Обьем 66')),
                ('acr67_temp', models.FloatField(blank=True, default=0.0, null=True, verbose_name='Температура 67')),
                ('acr67_press', models.FloatField(blank=True, default=0.0, null=True, verbose_name='Давление 67')),
                ('acr67_volume', models.FloatField(blank=True, default=0.0, null=True, verbose_name='Обьем 67')),
                ('acr68_temp', models.FloatField(blank=True, default=0.0, null=True, verbose_name='Температура 68')),
                ('acr68_press', models.FloatField(blank=True, default=0.0, null=True, verbose_name='Давление 68')),
                ('acr68_volume', models.FloatField(blank=True, default=0.0, null=True, verbose_name='Обьем 68')),
                ('acr69_temp', models.FloatField(blank=True, default=0.0, null=True, verbose_name='Температура 69')),
                ('acr69_press', models.FloatField(blank=True, default=0.0, null=True, verbose_name='Давление 69')),
                ('acr69_volume', models.FloatField(blank=True, default=0.0, null=True, verbose_name='Обьем 69')),
                ('acr70_temp', models.FloatField(blank=True, default=0.0, null=True, verbose_name='Температура 70')),
                ('acr70_press', models.FloatField(blank=True, default=0.0, null=True, verbose_name='Давление 70')),
                ('acr70_volume', models.FloatField(blank=True, default=0.0, null=True, verbose_name='Обьем 70')),
                ('acr82_temp1', models.FloatField(blank=True, default=0.0, null=True, verbose_name='Температура 82 верх')),
                ('acr82_temp2', models.FloatField(blank=True, default=0.0, null=True, verbose_name='Температура 82 низ')),
                ('acr82_press', models.FloatField(blank=True, default=0.0, null=True, verbose_name='Давление 82')),
                ('acr82_volume', models.FloatField(blank=True, default=0.0, null=True, verbose_name='Обьем 82')),
                ('acr83_temp1', models.FloatField(blank=True, default=0.0, null=True, verbose_name='Температура 83 верх')),
                ('acr83_temp2', models.FloatField(blank=True, default=0.0, null=True, verbose_name='Температура 83 низ')),
                ('acr83_press', models.FloatField(blank=True, default=0.0, null=True, verbose_name='Давление 83')),
                ('acr83_volume', models.FloatField(blank=True, default=0.0, null=True, verbose_name='Обьем 83')),
            ],
            options={
                'verbose_name_plural': 'Напорные акратофоры',
            },
        ),
        migrations.CreateModel(
            name='Nomenclature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GUID', models.CharField(max_length=36, verbose_name='GUID')),
                ('Nomenclature', models.CharField(max_length=150, verbose_name='Номенклатура')),
                ('GroupProduction', models.CharField(max_length=150, verbose_name='Группа продуктов')),
            ],
            options={
                'verbose_name_plural': 'Номенклатура',
            },
        ),
        migrations.CreateModel(
            name='prichina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(blank=True, default='Не определено', max_length=50, null=True, verbose_name='Подразделение')),
                ('prichina', models.CharField(blank=True, default='Не определена', max_length=50, null=True, verbose_name='Причина')),
            ],
            options={
                'verbose_name_plural': 'Причина простоя',
            },
        ),
        migrations.CreateModel(
            name='ProductionOutput2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Дата')),
                ('time', models.TimeField(verbose_name='Время')),
                ('production', models.IntegerField(verbose_name='Продукция линии')),
            ],
            options={
                'verbose_name_plural': 'Выпуск продукции линии 2',
            },
        ),
        migrations.CreateModel(
            name='ProductionOutput5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Дата')),
                ('time', models.TimeField(verbose_name='Время')),
                ('production', models.IntegerField(verbose_name='Продукция линии')),
            ],
            options={
                'verbose_name_plural': 'Выпуск продукции линии 5',
            },
        ),
        migrations.CreateModel(
            name='Speed2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Дата')),
                ('time', models.TimeField(verbose_name='Время')),
                ('speed', models.IntegerField(verbose_name='Скорость линии')),
            ],
            options={
                'verbose_name_plural': 'Производительность линии 2',
            },
        ),
        migrations.CreateModel(
            name='Speed5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Дата')),
                ('time', models.TimeField(verbose_name='Время')),
                ('speed', models.IntegerField(verbose_name='Скорость линии')),
            ],
            options={
                'verbose_name_plural': 'Производительность линии 5',
            },
        ),
        migrations.CreateModel(
            name='Table2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startdata', models.DateField(verbose_name='Дата начала простоя')),
                ('starttime', models.TimeField(verbose_name='Время начала простоя')),
                ('prostoy', models.TimeField(blank=True, null=True, verbose_name='Время простоя')),
                ('uchastok', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Где произошол простой')),
                ('prichina', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Причина')),
                ('otv_pod', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Ответственное подразделение')),
                ('comment', models.CharField(blank=True, default=' ', max_length=250, null=True, verbose_name='Комментарий')),
            ],
            options={
                'verbose_name_plural': 'Простои 2 линии',
            },
        ),
        migrations.CreateModel(
            name='Table5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startdata', models.DateField(verbose_name='Дата начала простоя')),
                ('starttime', models.TimeField(verbose_name='Время начала простоя')),
                ('prostoy', models.TimeField(blank=True, null=True, verbose_name='Время простоя')),
                ('uchastok', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Где произошол простой')),
                ('prichina', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Причина')),
                ('otv_pod', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Ответственное подразделение')),
                ('comment', models.CharField(blank=True, default=' ', max_length=250, null=True, verbose_name='Комментарий')),
            ],
            options={
                'verbose_name_plural': 'Простои 5 линии',
            },
        ),
        migrations.CreateModel(
            name='uchastok',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uchastok', models.CharField(blank=True, default='Не определено', max_length=50, null=True, verbose_name='Где произошол простой')),
            ],
            options={
                'verbose_name_plural': 'Участок линии',
            },
        ),
    ]
