# Generated by Django 4.2 on 2023-05-10 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temruk', '0002_productionoutput4_speed4_table4'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='speed4',
            name='speed',
        ),
        migrations.AddField(
            model_name='speed4',
            name='depal',
            field=models.IntegerField(blank=True, default=0.0, null=True, verbose_name='Скорость депалитизатор'),
        ),
        migrations.AddField(
            model_name='speed4',
            name='eticetka',
            field=models.IntegerField(blank=True, default=0.0, null=True, verbose_name='Скорость этикетки'),
        ),
        migrations.AddField(
            model_name='speed4',
            name='kapsula',
            field=models.IntegerField(blank=True, default=0.0, null=True, verbose_name='Скорость капсулятора'),
        ),
        migrations.AddField(
            model_name='speed4',
            name='triblok',
            field=models.IntegerField(blank=True, default=0.0, null=True, verbose_name='Скорость триблок'),
        ),
        migrations.AddField(
            model_name='speed4',
            name='ukladchik',
            field=models.IntegerField(blank=True, default=0.0, null=True, verbose_name='Скорость укладчика'),
        ),
        migrations.AddField(
            model_name='speed4',
            name='zakleichik',
            field=models.IntegerField(blank=True, default=0.0, null=True, verbose_name='Скорость заклейщика'),
        ),
    ]
