# Generated by Django 4.2 on 2023-05-17 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temruk', '0004_remove_speed5_speed_speed5_depal_speed5_eticetka_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startdata', models.DateField(verbose_name='Дата начала простоя')),
                ('starttime', models.TimeField(verbose_name='Время начала простоя')),
                ('prostoy', models.TimeField(blank=True, null=True, verbose_name='Время простоя')),
                ('uchastok', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Где произошол простой')),
                ('prichina', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Причина')),
                ('otv_pod', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Ответственное подразделение')),
                ('comment', models.CharField(blank=True, default=' ', max_length=250, null=True, verbose_name='Комментарий')),
            ],
            options={
                'verbose_name_plural': 'Простои 5 линии',
            },
        ),
    ]
