# Generated by Django 4.2 on 2023-05-22 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('temruk', '0005_tabletest'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tabletest',
            options={'verbose_name_plural': 'Простои Test'},
        ),
        migrations.RenameField(
            model_name='napacratofori',
            old_name='acr82_temp1',
            new_name='acr82_temp',
        ),
        migrations.RenameField(
            model_name='napacratofori',
            old_name='acr83_temp1',
            new_name='acr83_temp',
        ),
        migrations.RemoveField(
            model_name='napacratofori',
            name='acr82_temp2',
        ),
        migrations.RemoveField(
            model_name='napacratofori',
            name='acr83_temp2',
        ),
    ]
