# Generated by Django 4.2 on 2023-06-01 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temruk', '0007_remove_speed2_speed_speed2_depal_speed2_eticetka_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='bottleExplosion5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Дата')),
                ('time', models.TimeField(verbose_name='Время')),
                ('bottle', models.IntegerField(verbose_name='Взрыв')),
            ],
            options={
                'verbose_name_plural': 'Взрывы бутылок',
            },
        ),
    ]
