# Generated by Django 4.2 on 2023-06-14 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('temruk', '0008_bottleexplosion5'),
    ]

    operations = [
        migrations.DeleteModel(
            name='bottleExplosion',
        ),
    ]
