# Generated by Django 4.2 on 2023-06-14 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('temruk', '0010_productionoutput1_speed1_table1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductionOutput1',
        ),
        migrations.DeleteModel(
            name='Speed1',
        ),
        migrations.DeleteModel(
            name='Table1',
        ),
    ]
