# Generated by Django 4.2 on 2023-09-05 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('temruk', '0010_line2indicators_line5indicators'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Line2Indicators',
        ),
    ]
