# Generated by Django 4.2 on 2023-09-05 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('temruk', '0011_delete_line2indicators'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='line5indicators',
            options={'verbose_name_plural': 'Показатели линии 2'},
        ),
    ]
