# Generated by Django 4.2 on 2023-09-05 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temruk', '0012_alter_line5indicators_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='line5indicators',
            name='numbAcr',
            field=models.IntegerField(blank=True, default=0.0, null=True, verbose_name='Номер акратофора'),
        ),
    ]
