# Generated by Django 4.2 on 2023-09-05 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('temruk', '0014_line2indicators_alter_line5indicators_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='line2indicators',
            old_name='napPress',
            new_name='nappress',
        ),
        migrations.RenameField(
            model_name='line2indicators',
            old_name='napTemp',
            new_name='naptemp',
        ),
        migrations.RenameField(
            model_name='line2indicators',
            old_name='numbAcr',
            new_name='numbacr',
        ),
        migrations.RenameField(
            model_name='line5indicators',
            old_name='napPress',
            new_name='nappress',
        ),
        migrations.RenameField(
            model_name='line5indicators',
            old_name='napTemp',
            new_name='naptemp',
        ),
        migrations.RenameField(
            model_name='line5indicators',
            old_name='numbAcr',
            new_name='numbacr',
        ),
    ]
