# Generated by Django 4.2 on 2023-09-13 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temruk', '0015_rename_nappress_line2indicators_nappress_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionOutput1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Дата')),
                ('time', models.TimeField(verbose_name='Время')),
                ('production', models.IntegerField(verbose_name='Продукция линии')),
            ],
            options={
                'verbose_name_plural': 'Выпуск продукции линии 1',
            },
        ),
        migrations.DeleteModel(
            name='TableTest',
        ),
    ]
