# Generated by Django 4.2 on 2023-09-26 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temruk', '0016_productionoutput1_delete_tabletest'),
    ]

    operations = [
        migrations.CreateModel(
            name='CO2_Rozliv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Дата')),
                ('time', models.TimeField(verbose_name='Время')),
                ('volume', models.FloatField(blank=True, default=0.0, null=True, verbose_name='Обьем')),
            ],
            options={
                'verbose_name_plural': 'CO2 Розлив',
            },
        ),
    ]
