# Generated by Django 4.2 on 2023-09-29 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temruk', '0017_co2_rozliv'),
    ]

    operations = [
        migrations.CreateModel(
            name='CO2_Kupaj',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Дата')),
                ('time', models.TimeField(verbose_name='Время')),
                ('volume', models.FloatField(blank=True, default=0.0, null=True, verbose_name='Обьем')),
            ],
            options={
                'verbose_name_plural': 'CO2 Купахный',
            },
        ),
    ]
