# Generated by Django 4.2 on 2023-12-22 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temruk', '0019_filter2_filter4_filter5'),
    ]

    operations = [
        migrations.CreateModel(
            name='prichina_test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Guid_Prichina', models.CharField(blank=True, default='Не определено', max_length=36, null=True, verbose_name='Guid')),
                ('Key', models.CharField(blank=True, default='Не определено', max_length=50, null=True, verbose_name='Подразделение')),
                ('Prichina', models.CharField(blank=True, default='Не определена', max_length=50, null=True, verbose_name='Причина')),
            ],
            options={
                'verbose_name_plural': 'Причина простоя тест',
            },
        ),
        migrations.CreateModel(
            name='uchastok_test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Guid_Line', models.CharField(blank=True, default='Не определено', max_length=36, null=True, verbose_name='Guid')),
                ('Line', models.CharField(blank=True, default='Не определено', max_length=50, null=True, verbose_name='Линия')),
                ('Guid_Uchastok', models.CharField(blank=True, default='Не определено', max_length=36, null=True, verbose_name='Линия')),
                ('Uchastok', models.CharField(blank=True, default='Не определено', max_length=50, null=True, verbose_name='Где произошол простой')),
            ],
            options={
                'verbose_name_plural': 'Участок линии тест',
            },
        ),
    ]
