# Generated by Django 4.2 on 2023-12-25 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temruk', '0021_alter_uchastok_test_guid_uchastok'),
    ]

    operations = [
        migrations.AddField(
            model_name='table5',
            name='Guid_Prichina',
            field=models.CharField(blank=True, default='Не определено', max_length=36, null=True, verbose_name='Guid'),
        ),
    ]
