# Generated by Django 4.2 on 2023-12-25 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temruk', '0022_table5_guid_prichina'),
    ]

    operations = [
        migrations.AddField(
            model_name='table5',
            name='Guid_Uchastok',
            field=models.CharField(blank=True, default='Не определено', max_length=36, null=True, verbose_name='Guid участок'),
        ),
        migrations.AlterField(
            model_name='table5',
            name='Guid_Prichina',
            field=models.CharField(blank=True, default='Не определено', max_length=36, null=True, verbose_name='Guid причины'),
        ),
    ]
