# Generated by Django 4.2 on 2024-01-15 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temruk', '0023_table5_guid_uchastok_alter_table5_guid_prichina'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prichina',
            old_name='key',
            new_name='Key',
        ),
        migrations.RenameField(
            model_name='prichina',
            old_name='prichina',
            new_name='Prichina',
        ),
        migrations.RenameField(
            model_name='uchastok',
            old_name='uchastok',
            new_name='Uchastok',
        ),
        migrations.AddField(
            model_name='prichina',
            name='Guid_Prichina',
            field=models.CharField(blank=True, default='Не определено', max_length=36, null=True, verbose_name='Guid'),
        ),
        migrations.AddField(
            model_name='uchastok',
            name='Guid_Line',
            field=models.CharField(blank=True, default='Не определено', max_length=36, null=True, verbose_name='Guid'),
        ),
        migrations.AddField(
            model_name='uchastok',
            name='Guid_Uchastok',
            field=models.CharField(blank=True, default='Не определено', max_length=36, null=True, verbose_name='Guid участок'),
        ),
        migrations.AddField(
            model_name='uchastok',
            name='Line',
            field=models.CharField(blank=True, default='Не определено', max_length=50, null=True, verbose_name='Линия'),
        ),
    ]
