# Generated by Django 4.2 on 2024-01-19 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temruk', '0024_rename_key_prichina_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='table2',
            name='Guid_Prichina',
            field=models.CharField(blank=True, default='Не определено', max_length=36, null=True, verbose_name='Guid причины'),
        ),
        migrations.AddField(
            model_name='table2',
            name='Guid_Uchastok',
            field=models.CharField(blank=True, default='Не определено', max_length=36, null=True, verbose_name='Guid участок'),
        ),
        migrations.AddField(
            model_name='table4',
            name='Guid_Prichina',
            field=models.CharField(blank=True, default='Не определено', max_length=36, null=True, verbose_name='Guid причины'),
        ),
        migrations.AddField(
            model_name='table4',
            name='Guid_Uchastok',
            field=models.CharField(blank=True, default='Не определено', max_length=36, null=True, verbose_name='Guid участок'),
        ),
    ]
