# Generated by Django 4.2 on 2024-02-27 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('temruk', '0026_setproductionspeed'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SetProductionSpeed',
        ),
    ]
