# Generated by Django 4.2 on 2024-02-27 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temruk', '0028_setproductionspeed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setproductionspeed',
            name='line',
            field=models.IntegerField(verbose_name='Линия'),
        ),
    ]
