# Generated by Django 4.2 on 2024-03-11 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temruk', '0030_productiontime5'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionTime2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Дата')),
                ('time', models.TimeField(verbose_name='Время')),
                ('type_bottle', models.CharField(blank=True, default='', max_length=150, null=True, verbose_name='Тип бутылки')),
            ],
            options={
                'verbose_name_plural': 'Время работы на бутылке 2',
            },
        ),
        migrations.CreateModel(
            name='ProductionTime4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Дата')),
                ('time', models.TimeField(verbose_name='Время')),
                ('type_bottle', models.CharField(blank=True, default='', max_length=150, null=True, verbose_name='Тип бутылки')),
            ],
            options={
                'verbose_name_plural': 'Время работы на бутылке 4',
            },
        ),
    ]
