# Generated by Django 4.2 on 2024-03-14 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temruk', '0033_alter_table2_prichina'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table4',
            name='prichina',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Причина'),
        ),
        migrations.AlterField(
            model_name='table5',
            name='prichina',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Причина'),
        ),
    ]
